---
abstract: A Cache Engine with Adaptive Lifetime Control
author: 'Kazuho Oku <kazuhooku@gmail.com>'
build_requires:
  Cache::MemoryCache: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Cache-Adaptive
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0.3
  List::Util: 1.18
  Time::HiRes: 1.65
version: 0.03
